### ISSUE TITLE
This plugin generated a warning from the characteristic 'On'

### ISSUE THREAD

**Issue by Mor4vak** [newt10/homebridge-broadlink-rm-enhanced#19]
My log is spammed with this message:
`[homebridge-broadlink-rm-enhanced] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.`

**Comment by marcklemm** [comment]
Same here. I wasn't able to install any other broadlink plugins, except for this one. 
Yet this warning message pops up all the time and when trying to activate the learn button it spits out an error message saying that the device was not found.

The full error message of the "characteristic" problem is this:
`[homebridge-broadlink-rm-enhanced] Error
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1242:41)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1129:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:758:55
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/util/once.js:17:25
    at LearnIRAccessory.getCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-enhanced/base/accessory.js:161:5)
    at On.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:733:43
    at new Promise (<anonymous>:null:null)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:731:47)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1310:51)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.toHAP (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1293:24)
    at _loop_1 (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:432:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:450:21
    at new Promise (<anonymous>:null:null)
    at Switch.Service.toHAP (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:356:16)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:827:112
    at Array.map (<anonymous>:null:null)
    at Accessory.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:827:72)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Accessory.toHAP (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:816:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:837:78
    at Array.map (<anonymous>:null:null)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:837:34)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by Mor4vak** [comment]
me learn button works

**Comment by newt10** [comment]
I am going to try to look into this. Thanks for flagging.

**Comment by newt10** [comment]
This should now be fixed. Please reopen bug and share details if you see a problem.
