### ISSUE TITLE
Install fails trying to contact a local ip address that doesn't exist 

### ISSUE THREAD

**Issue by witchdrash** [newt10/homebridge-broadlink-rm-enhanced#25]
root@homebridge-vm:~/.npm/_logs# cat 2021-07-22T08_05_16_127Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'homebridge-broadlink-rm-enhanced@latest'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose npm-session 3448646ae9a70247
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for homebridge-broadlink-rm-enhanced@latest request to http://192.168.1.119:4873/homebridge-broadlink-rm-enhanced failed, reason: connect EHOSTUNREACH 192.168.1.119:4873
8 timing stage:rollbackFailedOptional Completed in 6ms
9 timing stage:runTopLevelLifecycles Completed in 6544ms
10 verbose type system
11 verbose stack FetchError: request to http://192.168.1.119:4873/homebridge-broadlink-rm-enhanced failed, reason: connect EHOSTUNREACH 192.168.1.119:4873
11 verbose stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:315:20)
11 verbose stack     at Socket.socketErrorListener (_http_client.js:469:9)
11 verbose stack     at Socket.emit (events.js:315:20)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:106:8)
11 verbose stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
12 verbose cwd /homebridge
13 verbose Linux 4.19.103-boot2docker
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-broadlink-rm-enhanced@latest"
15 verbose node v14.16.1
16 verbose npm  v6.14.12
17 error code EHOSTUNREACH
18 error errno EHOSTUNREACH
19 error request to http://192.168.1.119:4873/homebridge-broadlink-rm-enhanced failed, reason: connect EHOSTUNREACH 192.168.1.119:4873
20 verbose exit [ 1, true ]

**Comment by witchdrash** [comment]
There is no device on my network with the address 192.168.1.119

**Comment by witchdrash** [comment]
Environmental issue at my end
